version: "3.9"

#name: attestation-suite-indexer-btc

services: 
  indexer:
    image: attestation-suite
    volumes:
      - ./../credentials:/app/attestation-suite-config
    environment:
      MYSQL_ROOT_PASSWORD: "test123"
    command:
      "./docker/scripts/indexer-btc.sh"
    depends_on:
      - database

  verification-server:
    image: attestation-suite
    volumes:
      - ./../credentials:/app/attestation-suite-config
    environment:
      MYSQL_ROOT_PASSWORD: "test123"
    command:
      "./docker/scripts/verification-server-btc.sh"
    depends_on:
      - database
    ports:
      - "9500:9000"  # btc 9500   

  database:
    image: mysql:8-debian
    container_name: indexer-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "test123"
    cap_add:
      - SYS_NICE
    #volumes:
    #  - ./mysql-conf.d/:/etc/mysql/conf.d
    #  - ./mysql-initdb/:/docker-entrypoint-initdb.d
    #  - ./mysql-data/:/var/lib/mysql

  
        

