

services:
  indexer:
    image: attestation-suite
    volumes:
      - ../credentials:/app/attestation-suite-config
    container_name: indexer-xrp-indexer
    command: indexer xrp
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database

  verification-server:
    image: attestation-suite
    volumes:
      - ../credentials:/app/attestation-suite-config
    container_name: indexer-xrp-verification-server
    command: verification-server xrp
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database
    ports:
      - 9500:9000

  database:
    image: mysql:8-debian
    container_name: indexer-xrp-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    cap_add:
      - SYS_NICE
    # volumes:
    #   - ./mysql-conf.d/:/etc/mysql/conf.d
    #   - ./mysql-initdb/:/docker-entrypoint-initdb.d
    #   - ./mysql-data/:/var/lib/mysql

  ripple-node:
    image: flarefoundation/rippled:1.9.4
    restart: unless-stopped
    ports:
      - ${BIND_IP}:15005:5005   # port_rpc_admin_local
      - ${BIND_IP}:16006:6006   # port_ws_admin_local
      - ${BIND_IP}:11235:51235 # port_peer
      - ${BIND_IP}:11234:51234 # port_rpc_public
      - ${BIND_IP}:11233:51233 # port_ws_public
      - ${BIND_IP}:10051:50051 # port_grpc
    volumes:
      - ripple-testnet-data:/opt/ripple/.ripple/db
      - ../node-configs/testnet/ripple/rippled.conf:/opt/ripple/.ripple/rippled.conf
      - ../node-configs/testnet/validators.txt:/opt/ripple/.ripple/validators.txt

volumes:
  ripple-testnet-data:
