

services:
  indexer:
    image: attestation-suite
    volumes:
      - ../../credentials:/app/attestation-suite-config
    container_name: indexer-btc-indexer
    command: indexer btc
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database

  verification-server:
    image: attestation-suite
    volumes:
      - ../../credentials:/app/attestation-suite-config
    container_name: indexer-btc-verification-server
    command: verification-server btc
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    depends_on:
      - database
    ports:
      - 9500:9000

  database:
    image: mysql:8-debian
    container_name: indexer-btc-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    cap_add:
      - SYS_NICE
    # volumes:
    #   - ./mysql-conf.d/:/etc/mysql/conf.d
    #   - ./mysql-initdb/:/docker-entrypoint-initdb.d
    #   - ./mysql-data/:/var/lib/mysql

  bitcoin-node:
    image: flarefoundation/bitcoin:23.0
    restart: unless-stopped
    ports:
      - 18332:18332
      - 18333:18333
    volumes:
      - bitcoin-testnet-data:/opt/bitcoin/.bitcoin/db
      - ../node-configs/testnet/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

volumes:
  bitcoin-testnet-data:
